/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export { }
declare global {
    module "*.vue" {
        import { DefineComponent } from "vue"
        const component: DefineComponent<{}, {}, any>
        export default component
    }
}
